/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MaintenanceOrdersObjectPageObjectPage journey");

        opaTest("Navigate to MaintenanceOrdersObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheMaintenanceOrdersListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheMaintenanceOrdersListGenerated.onTable().iCheckRows();
            When.onTheMaintenanceOrdersListGenerated.onTable().iPressRow(0);

            Then.onTheMaintenanceOrdersObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheMaintenanceOrdersObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheMaintenanceOrdersObjectPageGenerated.iPressSectionIconTabFilterButton("FieldGroup::General");
            Then.onTheMaintenanceOrdersObjectPageGenerated.iCheckSection({ section: "FieldGroup::General" });
            Then.onTheMaintenanceOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "orderNumber" });
            Then.onTheMaintenanceOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "equipment_ID" });
            Then.onTheMaintenanceOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "description" });
            Then.onTheMaintenanceOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "priority" });
            Then.onTheMaintenanceOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "status" });
            Then.onTheMaintenanceOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "responsible" });
            Then.onTheMaintenanceOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "notes" });
            Then.onTheMaintenanceOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "plannedStart" });
            Then.onTheMaintenanceOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "plannedEnd" });
            When.onTheMaintenanceOrdersObjectPageGenerated.iPressSectionIconTabFilterButton("workItems::LineItem");
            Then.onTheMaintenanceOrdersObjectPageGenerated.iCheckSection({ section: "workItems::LineItem" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});